# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='description',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
