# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20170316_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
